### PR TITLE
feat(mte): Upgrade mutation testing elements to 2.0.0

### PR DESCRIPTION
**Pull request by rouke-broersma**
fix stryker-mutator/stryker-net#2499

### CODE REVIEW

**Comment by rouke-broersma** [comment]
@nicojs does this look alright or should more be done to support the new schema in the dashboard?

**Review by nicojs — APPROVED** [review]
Sure. Love the new tests 🙂

**Comment by rouke-broersma** [comment]
@nicojs any chance you could release it? :D

**Comment by nicojs** [comment]
Sure

**Comment by nicojs** [comment]
It's being released: https://github.com/stryker-mutator/stryker-dashboard/actions/runs/4903136799

**Comment by vbreuss** [comment]
Thanks for the quick update, @rouke-broersma !
It's much appreciated 👍

**Pull request merged**
