### PR TITLE
[Badge API] Show 100% coverage as bright green instead of green

### PR DESCRIPTION
**Pull request by 0xced**

### CODE REVIEW

**Comment by nicojs** [comment]
neat idea :)

**Comment by 0xced** [comment]
Any chance to get this merged?

I'd like to add a mutation score badge but it looks a little bit out of place among other bright green badges. 😉

[Continuous Integration](https://github.com/serilog-contrib/serilog-formatting-log4net/actions?query=workflow%3A%22Continuous+Integration%22)

[Coverage](https://codecov.io/gh/serilog-contrib/serilog-formatting-log4net)

[Code Quality](https://app.codacy.com/gh/serilog-contrib/serilog-formatting-log4net)

[Mutation Score](https://dashboard.stryker-mutator.io/reports/github.com/serilog-contrib/serilog-formatting-log4net/main)

**Comment by 0xced** [comment]
Hey @nicojs, do you have plan to merge this?

**Comment by 0xced** [comment]
My comment from [Sep 14, 2021](https://github.com/stryker-mutator/stryker-dashboard/pull/202#issuecomment-918873625) as a picture for reference because once merged it should all look bright green. 😉
image

**Pull request merged**
