### PR TITLE
fix: add unsafe-eval to csp script-src directives

### LINKED ISSUE #592: Realtime report does not work due to compression
image

@hugo-vrijswijk you changed something with the CSP a while ago, did this get released (or was this a fix for this)?

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
(Potentially) fixes #592

Ideally we would be able to disable unsafe-eval (and unsafe-inline), but this at least gets things working again

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
@xandervedder  I don't really know how to test the real-time report, so could you test this on acc?

**Comment by xandervedder** [comment]
Still not working.. hmm I'll have to check if it still works locally..

**Comment by hugo-vrijswijk** [comment]
Could you post a screenshot of the console log? Its 100% this change, but it might need some adjustments

**Comment by xandervedder** [comment]
To test in real-time, you would need a .net project and use the following arguments: `dotnet stryker --reporter "dashboard" -o:dashboard --dashboard-api-key "key_here"`

You would also need to configure .net stryker to use the acceptance environment:
```
{
  "stryker-config": {
    "dashboard-url": "https://stryker-dashboard-acceptance.azurewebsites.net",
    "project-info": {
      "version": "main"
    }
  }
}
```
---
The error shown in the issue was caused by one of my extensions, I have removed that one (but I doubt it would work now)

**Comment by xandervedder** [comment]
Tested locally, also does not work, let me try to pinpoint when it actually did work.

**Pull request closed without merging**
